from __future__ import annotations

import re
from collections import Counter
from pathlib import Path
from typing import Any

# Path to the paper-finder assets directory (resolved at import time)
_ASSETS_DIR = Path(__file__).resolve().parents[2] / "assets"
_JOURNAL_LIST_PATH = _ASSETS_DIR / "journal_list.json"

_STOPWORDS = {
    "about",
    "across",
    "analysis",
    "approach",
    "based",
    "data",
    "from",
    "into",
    "model",
    "models",
    "method",
    "methods",
    "paper",
    "study",
    "studies",
    "system",
    "using",
    "with",
}


def _top_counter(counter: Counter[str], *, limit: int = 10, min_count: int = 1) -> list[dict[str, int | str]]:
    result: list[dict[str, int | str]] = []
    for key, count in counter.most_common():
        if count < min_count:
            continue
        result.append({"value": key, "count": count})
        if len(result) >= limit:
            break
    return result


def _extract_title_terms(title: str) -> list[str]:
    tokens = re.findall(r"[A-Za-z][A-Za-z0-9+-]{2,}", title)
    result: list[str] = []
    for token in tokens:
        lowered = token.lower()
        if lowered in _STOPWORDS:
            continue
        result.append(lowered)
    return result


_NBER_SOURCE_ID = "I1321305853"
# Aliases that represent working-paper sources (not journal titles in Zotero)
_WORKING_PAPER_KEYWORDS = {
    "nber", "working paper", "cepr", "ssrn", "browse", "repec",
}

# ── Journals in journal_list.json (key = lowercase title, value = title_to_alias result) ──
# Generated by: python3 -c "from client import _title_to_alias; print(repr(_title_to_alias('Title')))"
# Only entries whose title appears exactly in journal_list.json are included here.
_JOURNAL_TITLE_NORMALIZATIONS: dict[str, str] = {
    # Urban / Housing (AAA/AA in journal_list.json)
    "urban studies": "USTU",
    "cities": "CITI",
    "regional science and urban economics": "RSUECO",
    "real estate economics": "REECO",
    "journal of public economics": "JPECO",
    "journal of urban economics": "JUECO",
    "journal of housing economics": "JHECO",
    "journal of development economics": "JDECO",
    "journal of labor economics": "JLECO",
    "world development": "WDEV",
    # Core econ/finance (AAA/AA)
    "american economic review": "AER",
    "the american economic review": "AER",
    "a.e.r.": "AER",
    "journal of political economy": "JPE",
    "j. polit. econ.": "JPE",
    "the journal of political economy": "JPE",
    "quarterly journal of economics": "QJE",
    "q.j.e.": "QJE",
    "the quarterly journal of economics": "QJE",
    "review of economic studies": "RESTU",
    "rev. econ. stud.": "RESTU",
    "the review of economic studies": "RESTU",
    "review of economics and statistics": "RESTA",
    "rev. econ. stat.": "RESTA",
    "the review of economics and statistics": "RESTA",
    "economica": "ECONM",
    "explorations in economic history": "EXPEH",
    "journal of economic growth": "JEGRO",
    "review of economic dynamics": "REV dy",
    "journal of economic theory": "JECONt",
    "games and economic behavior": "GAEBE",
    "journal of environmental economics and management": "JEEconM",
    "international economic review": "interER",
    "economic inquiry": "econ in",
    "journal of economic behavior & organization": "JEBEOR",
    "journal of economic geography": "JECONg",
    "j. econ. geogr.": "JECONg",
    "world bank economic review": "WORLBE",
    "journal of the japanese and international economies": "JJIE",
}


def _load_journal_title_to_alias() -> dict[str, str]:
    """Build a lowercase-title → alias mapping from journal_list.json."""
    import json
    mapping: dict[str, str] = {}
    try:
        data = json.loads(_JOURNAL_LIST_PATH.read_text(encoding="utf-8"))
        if isinstance(data, list):
            for entry in data:
                if not isinstance(entry, dict):
                    continue
                title = str(entry.get("title") or "").strip().lower()
                alias = str(entry.get("alias") or "").strip()
                openalex_id = str(entry.get("openalex_id") or "").strip()
                if title and (alias or openalex_id):
                    mapping[title] = alias or f"S{openalex_id.lstrip('S')}"
    except Exception:
        pass
    # Add known alias → alias entries for well-known journals not in the list
    known_aliases: dict[str, str] = {
        "aer": "AER",
        "aper": "AER",
        "jpe": "JPE",
        "qje": "QJE",
        "restud": "ReStud",
        "jpube": "JPubE",
        "jue": "JUE",
        "jho": "JHO",
        "rsue": "RSUE",
        "jde": "JDE",
        "jle": "JLE",
        "wd": "WD",
        "jeg": "JEG",
        "restat": "ReStat",
        "economica": "Economica",
        "eeh": "EEH",
        "ej": "EJ",
        "ier": "IER",
        "geb": "GEB",
    }
    for k, v in known_aliases.items():
        if k not in mapping:
            mapping[k] = v
    return mapping


def _normalize_journal_title(title: str) -> str:
    """Strip leading 'The ', lowercase, and collapse whitespace."""
    t = title.strip()
    if t.lower().startswith("the "):
        t = t[4:]
    return re.sub(r"\s+", " ", t).lower()


def build_suggested_sources(venue_counter: Counter[str], *, top_n: int = 10) -> list[str]:
    """Suggest OpenAlex source aliases from a Counter of publication titles.

    The Zotero field ``publication_title`` (e.g. "American Economic Review")
    is matched against known journal titles and aliases to produce a list of
    short source identifiers (e.g. "AER", "JPE") suitable for use in
    ``profile.sources`` and for passing to ``search_works(source=...)``.
    """
    title_map = _load_journal_title_to_alias()
    seen: set[str] = set()
    suggestions: list[str] = []

    # NBER always first if present at all
    nber_count = venue_counter.get("national bureau of economic research", 0) or \
                 venue_counter.get("nber", 0) or \
                 venue_counter.get("NBER", 0) or \
                 venue_counter.get("National Bureau of Economic Research", 0)
    if nber_count > 0:
        suggestions.append("NBER")
        seen.add("nber")

    # Sort venues by count descending, then by title for stability
    for venue_raw, count in sorted(venue_counter.items(), key=lambda x: (-x[1], x[0])):
        if len(suggestions) >= top_n:
            break
        normalized = _normalize_journal_title(venue_raw)
        # Skip working-paper labels
        if normalized in _WORKING_PAPER_KEYWORDS or any(
            kw in normalized for kw in _WORKING_PAPER_KEYWORDS
        ):
            continue
        # Direct lookup
        if normalized in title_map:
            alias = title_map[normalized]
            if alias.lower() not in seen:
                suggestions.append(alias)
                seen.add(alias.lower())
                continue
        # Heuristic matching via the normalizations table
        if normalized in _JOURNAL_TITLE_NORMALIZATIONS:
            alias = _JOURNAL_TITLE_NORMALIZATIONS[normalized]
            if alias.lower() not in seen:
                suggestions.append(alias)
                seen.add(alias.lower())
                continue

    return suggestions[:top_n]


def build_profile_evidence_summary(
    items: list[dict],
    *,
    collections: list[str],
    tags: list[str],
    applied_limit: int,
) -> dict:
    tag_counter: Counter[str] = Counter()
    title_counter: Counter[str] = Counter()
    venue_counter: Counter[str] = Counter()
    year_counter: Counter[str] = Counter()

    for item in items:
        for tag in item.get("tags", []):
            tag_counter[tag] += 1
        for term in _extract_title_terms(str(item.get("title") or "")):
            title_counter[term] += 1
        venue = str(item.get("publication_title") or "").strip()
        if venue:
            venue_counter[venue] += 1
        year = str(item.get("year") or "").strip()
        if year:
            year_counter[year] += 1

    suggested_sources = build_suggested_sources(venue_counter, top_n=10)
    return {
        "basis": {
            "collections": collections,
            "tags": tags,
            "item_count": len(items),
            "applied_limit": applied_limit,
        },
        "summary": {
            "top_tags": _top_counter(tag_counter, limit=12, min_count=1),
            "top_title_terms": _top_counter(title_counter, limit=15, min_count=2),
            "top_publication_titles": _top_counter(venue_counter, limit=10, min_count=1),
            "top_years": _top_counter(year_counter, limit=10, min_count=1),
            "sample_titles": [item["title"] for item in items[:10] if item.get("title")],
            "suggested_sources": [{"value": s} for s in suggested_sources],
        },
        "items": items,
    }
